[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "EpASoVWxRY8SEgkwFrVpYSr9qYUQPaXjswhEw7NB7K9Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mrabdu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

